CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                    name VARCHAR(255),
                    email VARCHAR(255),
                    birthDay DATE);
CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                     name VARCHAR(255),
                     airDate DATE,
                     airTime TIME,
                     basePrice DOUBLE,
                     rating VARCHAR(255),
                     auditorium VARCHAR(255));
CREATE TABLE tickets (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                     eventId INT,
                     userId INT,
                     seat INT,
                     isPurchased BOOLEAN,
                     FOREIGN KEY (eventId) REFERENCES events (id),
                     FOREIGN KEY (userId) REFERENCES users (id));
CREATE TABLE counters (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                       counterType VARCHAR(255),
                       keyName VARCHAR(255),
                       valueCounter VARCHAR(255));